// <auto-generated />
namespace CaisseServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V100 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V100));
        
        string IMigrationMetadata.Id
        {
            get { return "201906080110447_V1.0.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
